# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test on Python ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: .python-version
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          python-version: .python-version
    - name: Install dependencies
      run: |
        uv sync
    - name: Test
      run: |
        uv run test/test_profileit.py
  
